name: CI
on:
  push:
    branches:
      - 'master'

jobs:
  build:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres
#        env:
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_USER: postgres
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          # Maps tcp port 5432 on service container to the host
#          - 5432:5432
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          ref: master
#      - uses: actions/setup-go@v1
#        with:
#          go-version: '1.13.4'
#      - name: Test
#        run: go test ./...

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.4'
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
